"""Pop's plugins: the catalog, the categories, and what each page says.

The catalog is Pop's own (Pop/Plugins/PluginCatalog.swift in github.com/whrss9527/pop, with the English
names and summaries from Pop/Resources/en.lproj/Localizable.strings, and `accepts` from each plugin's
PluginInfo); the order within a category follows the plugin table in docs/guide.md. Update it when Pop
adds, renames or removes a plugin, and add the plugin's page content in plugin_data/<category>.py.
"""
import re

SLUGS = {"airDrop": "airdrop"}


class P:
    """One plugin. funcs: the action IDs it provides (for pop://run?plugin=…); accepts: the kinds of
    content it handles, from its PluginInfo (empty: always available)."""

    def __init__(self, pid, cat, symbol, funcs, accepts, en, zh, en_sum, zh_sum):
        self.id = pid
        self.cat = cat
        self.symbol = symbol
        self.funcs = funcs
        self.accepts = accepts
        self.en = en
        self.zh = zh
        self.en_sum = en_sum
        self.zh_sum = zh_sum

    def name(self, lang):
        return self.zh if lang == "zh" else self.en

    def summary(self, lang):
        return self.zh_sum if lang == "zh" else self.en_sum

    @property
    def slug(self):
        """The page's address: /pop/plugins/<slug>/ (Pop's plugin ID, in lower case with dashes)."""
        if self.id in SLUGS:
            return SLUGS[self.id]
        s = re.sub(r"(?<=[a-z0-9])(?=[A-Z])|(?<=[A-Z])(?=[A-Z][a-z])", "-", self.id)
        return s.lower()


# key, English, Chinese, one line in each language
CATS = [
    ("text", "Text", "文字",
     "Read, tidy, extract and present the text you select.",
     "朗读、整理、提取、展示选中的文字。"),
    ("convert", "Convert", "转换",
     "Turn data from one shape into another: tables, Markdown, dates, numbers, colors.",
     "把数据换个样子：表格、Markdown、日期、数字、颜色。"),
    ("developer", "Developer", "开发",
     "Small tools for code: hashes, QR codes, JWTs, regular expressions, cron.",
     "写代码时的小工具：哈希、二维码、JWT、正则、cron。"),
    ("screen", "Screen & Images", "屏幕与图片",
     "Capture the screen and work on images without opening an editor.",
     "截屏、识别，不打开修图软件就能处理图片。"),
    ("recording", "Recording & Presenting", "录屏和演示",
     "Record the screen or your voice, and point things out while you present.",
     "录屏、录音，演示时把要讲的地方指给大家看。"),
    ("files", "Files & System", "文件和系统",
     "Work on the files you select in Finder, and on the Mac itself.",
     "处理访达里选中的文件，也管管这台 Mac。"),
]
CAT_KEYS = [c[0] for c in CATS]

PLUGINS = [
    # text
    P("screenshotTranslate", "text", "translate", ["screenshotTranslate"], [],
      "Translate Screenshot", "截图翻译",
      "Select an area of the screen, recognize its text and translate it (offline)",
      "框选屏幕上的一块区域，识别里面的文字并翻译（离线）"),
    P("speak", "text", "speaker.wave.2", ["speak", "speakToFile"], ["text"],
      "Speak", "朗读",
      "Read the selected text aloud with a system voice; use it again while speaking to stop. It can also save the speech as an audio file",
      "用系统语音朗读选中的文字，朗读中再用一次就停止；也能读出来存成音频文件"),
    P("webCapture", "text", "arrow.down.doc", ["webCapture"], ["url"],
      "Save Web Page", "网页存档",
      "Save the whole page at the selected URL to Downloads as one long PDF (with selectable, searchable text) or a long image, or save just the article text as Markdown",
      "把选中的网址整页存成一页长 PDF（文字能选、能搜）、一张长图，或者只把正文存成 Markdown，放在「下载」里"),
    P("textImage", "text", "text.below.photo", ["textImage"], ["text"],
      "Text to Image", "文字转图片",
      "Lay out the selected text as a long image that reads well on a phone (1080 pixels wide) on a white, cream or dark background; copy it, save it or pin it to the screen",
      "把选中的文字排成一张手机上看着舒服的长图（宽 1080 像素），白底、米黄、深色三种底色，可以复制、存储或贴到屏幕上"),
    P("largeType", "text", "textformat.size", ["largeType"], ["text"],
      "Large Type", "大字显示",
      "Show the selected text across the whole screen, handy for showing someone a phone number, Wi-Fi password or pickup code; click or press any key to close",
      "把选中的文字铺满整个屏幕，给别人看电话号码、Wi-Fi 密码、取件码都方便；点一下或按任意键关闭"),
    P("fontPreview", "text", "textformat", ["fontPreview"], [],
      "Font Preview", "字体预览",
      "Show the selected text (or a sample) in every font on your Mac, filter by Chinese, Western, monospaced or favorite fonts and only those that can show all of it; copy the font name or CSS, or copy it as an image; select font files to preview and install them",
      "用这台 Mac 上的每一种字体显示选中的文字（没选中时用示例），按中文、西文、等宽、收藏筛选，只看能完整显示的；复制字体名、CSS，或者复制成图片；选中字体文件时先预览再安装"),
    P("textCleanup", "text", "text.alignleft", ["textCleanup"], ["text"],
      "Clean Up Text", "文字整理",
      "Join lines, remove blank lines and extra spaces, space Chinese and Latin text, full-width to half-width, Simplified ↔ Traditional Chinese, Pinyin, sort and deduplicate lines",
      "合并换行、去掉空行和多余空格、中英文之间加空格、全角转半角、简繁转换、拼音、按行排序去重"),
    P("extractInfo", "text", "text.magnifyingglass", ["extractInfo"], ["text"],
      "Extract Info", "提取信息",
      "Find links, email addresses, phone numbers and IP addresses in text and copy them one by one or together",
      "从一段文字里找出链接、邮箱、电话号码和 IP 地址，逐个复制或者一起复制"),
    P("idNumber", "text", "person.text.rectangle", ["idNumber"], ["text", "number"],
      "ID Numbers", "证件号码",
      "Chinese ID numbers, unified social credit codes and bank card numbers: check the check digit and read out birth date, age, sex, region and registration authority, offline",
      "身份证号、统一社会信用代码、银行卡号：检查校验位，读出出生日期、年龄、性别、地区和登记管理部门，不联网"),
    P("lineTools", "text", "list.bullet.rectangle", ["lineTools"], ["text"],
      "Lines", "按行处理",
      "Quote and comma-separate a list (for SQL IN), convert to a JSON array, add or remove numbering, reverse, shuffle; split a comma-separated line into lines",
      "一列文字加引号和逗号（SQL 的 IN 列表）、转 JSON 数组、加减序号、倒序、打乱；一行用逗号隔开的拆成多行"),
    P("reminder", "text", "checklist", ["reminder"], ["text"],
      "Add to Reminders", "加到提醒事项",
      "Find a time in the selected Chinese text (明天下午 3 点, 周五, 10 月 8 日, 半小时后…) and add it to Reminders or Calendar",
      "从选中的文字里认出时间（明天下午 3 点、周五、10 月 8 日、半小时后……），加到「提醒事项」或者「日历」"),
    P("spellCheck", "text", "text.badge.checkmark", ["spellCheck"], ["foreignText"],
      "Spell Check", "拼写检查",
      "Find misspelled words and suggest corrections you can apply directly (built-in macOS spell checking, offline)",
      "找出外文里拼错的词，给出改法，可以直接换成改好的文字（系统自带的拼写检查，离线）"),
    P("textDiff", "text", "arrow.left.arrow.right.square", ["textDiff"], ["text"],
      "Compare Text", "文本对比",
      "Compare the selected text with the text on the clipboard and mark deletions and additions",
      "把选中的文字和剪贴板里的文字对比，标出删去和新增的地方"),
    P("emojiSymbols", "text", "face.smiling", ["emojiSymbols"], [],
      "Emoji & Symbols", "表情和符号",
      "Search emoji in Chinese, pinyin or English (“笑”, “猫”, “smile”), plus everyday special symbols: check marks, arrows, circled numbers, math, units and currency, Greek letters, superscripts and subscripts. Click one to insert it where you are typing, or select a word first to replace it with an emoji",
      "用中文、拼音或者英文搜表情（「笑」「猫」「smile」），也有常用的特殊符号：对勾、箭头、带圈数字、数学符号、单位和货币、希腊字母、上下标；点一下插到正在打字的地方。选中一个词再用，能直接换成表情"),
    P("quickNote", "text", "tray.and.arrow.down", ["quickNote"], ["text"],
      "Inbox", "收集箱",
      "Append the selected text to “Documents/Pop 收集箱.md”",
      "把选中的文字追加到「文稿/Pop 收集箱.md」"),
    # convert
    P("numberStats", "convert", "sum", ["numberStats"], ["text"],
      "Number Statistics", "数字统计",
      "Get the sum, average, median, max and min of a list of numbers",
      "选中一列或一串数字，算出合计、平均、中位数、最大、最小"),
    P("chart", "convert", "chart.bar.xaxis", ["chart"], ["text"],
      "Chart", "生成图表",
      "Turn a selected table, lines of “name value” or a list of numbers into a column, bar, line or pie chart, then copy it as an image or save it to Downloads",
      "选中表格、一行一个「名字 数值」或者一串数，画成柱状图、条形图、折线图或者饼图，复制成图片或者存到「下载」"),
    P("changeCase", "convert", "textformat", ["changeCase"], ["text"],
      "Case", "大小写",
      "Convert between uppercase, lowercase, camelCase, snake_case and more",
      "大写、小写、驼峰、下划线等写法互相转换"),
    P("encodeDecode", "convert", "chevron.left.forwardslash.chevron.right", ["encodeDecode"], ["text"],
      "Encode & Decode", "编码转换",
      "Encode and decode Base64, URL, Unicode and HTML entities",
      "Base64、URL、Unicode、HTML 实体的编码和解码"),
    P("yamlJSON", "convert", "arrow.left.arrow.right.square", ["yamlJSON"], ["text"],
      "YAML ↔ JSON", "YAML 和 JSON",
      "Convert selected JSON to YAML or YAML to JSON, keeping key order",
      "选中 JSON 转成 YAML，选中 YAML 转成 JSON，键的顺序不变"),
    P("formatXML", "convert", "chevron.left.forwardslash.chevron.right", ["formatXML"], ["text"],
      "Format XML", "XML 格式化",
      "Format or minify the selected XML (SVG, plist and XHTML too)",
      "格式化或压缩选中的 XML（也认 SVG、plist、XHTML）"),
    P("formatSQL", "convert", "cylinder.split.1x2", ["formatSQL"], ["text"],
      "Format SQL", "SQL 格式化",
      "Put each clause of the selected SQL on its own line, uppercase keywords and indent subqueries, or squeeze it onto one line",
      "把选中的 SQL 按子句分行、关键字大写、子查询缩进，也可以压成一行"),
    P("tableConvert", "convert", "tablecells", ["tableConvert"], ["text"],
      "Convert Table", "表格转换",
      "Convert between text copied from spreadsheets, CSV and Markdown tables, or to JSON",
      "从表格软件复制的文字、CSV、Markdown 表格互相转换，也能转成 JSON"),
    P("markdown", "convert", "doc.richtext", ["markdownPreview", "markdownCopy"], ["text"],
      "Markdown Rich Text", "Markdown 富文本",
      "Preview the selected Markdown formatted, or copy it as formatted text that keeps its formatting when pasted into documents, mail or notes",
      "把选中的 Markdown 显示成排好版的样子，或者转成带格式的文字复制下来，粘贴到文稿、邮件、备忘录里保留格式"),
    P("toMarkdown", "convert", "doc.plaintext", ["toMarkdown"], ["text"],
      "Convert to Markdown", "转成 Markdown",
      "Convert formatted text selected in web pages and documents to Markdown: headings, lists, links, bold, code, tables",
      "把网页、文档里选中的带格式文字转成 Markdown：标题、列表、链接、粗体、代码、表格"),
    P("markdownTOC", "convert", "list.bullet.rectangle", ["markdownTOC"], ["text"],
      "Markdown Table of Contents", "Markdown 目录",
      "Create a table of contents from the headings in the selected Markdown, with links to each heading (GitHub-style anchors)",
      "按选中的 Markdown 里的标题生成目录，点链接能跳到对应的标题（锚点和 GitHub 的写法一样）"),
    P("dateSpan", "convert", "calendar.badge.clock", ["dateSpan"], ["text"],
      "Date Difference", "日期计算",
      "Select two dates (e.g. “2026-09-29 to 2026-12-25”) to get the days, weeks and months between them and how many are workdays",
      "选中两个日期（比如「2026-09-29 到 2026-12-25」），算出相差多少天、几周、几个月，其中有多少个工作日"),
    P("worldTime", "convert", "globe.asia.australia", ["worldTime"], [],
      "Time Zones", "时区换算",
      "Select a time such as “3pm PST” or “9 pm Beijing time” to see it in the cities you use. Drag the slider to try other times and find when everyone is at work",
      "选中「3pm PST」「北京时间晚上 9 点」这样的时间，换算成常用的几个城市的时间；拖动滑块看别的时刻，找大家都在上班的时间开会"),
    P("numberConvert", "convert", "number.circle", ["numberConvert"], ["number"],
      "Numbers", "数字转换",
      "Bases, thousands separators, RMB in words",
      "进制转换、千分位、人民币大写"),
    P("contrast", "convert", "circle.lefthalf.filled", ["contrast"], ["text"],
      "Contrast", "对比度",
      "Select two colors (e.g. “#333333 #FFFFFF”) to get the text/background contrast ratio and whether it meets WCAG AA and AAA",
      "选中两个颜色（比如「#333333 #FFFFFF」），算出文字和背景的对比度，看是否达到 WCAG 的 AA、AAA"),
    # developer
    P("hash", "developer", "number.square", ["hash"], ["text", "files"],
      "Hash", "哈希",
      "Compute MD5, SHA-1, SHA-256 and SHA-512 of text or files",
      "计算文字或文件的 MD5、SHA-1、SHA-256、SHA-512"),
    P("qrCode", "developer", "qrcode", ["qrCode"], ["text", "image", "imageFile"],
      "QR Code", "二维码",
      "Generate a QR code from text or a link (letters and digits can also become a barcode); with an image selected, read the QR codes and barcodes in it",
      "把文字或链接生成二维码（英文字母和数字还能生成条形码）；选中图片时识别里面的二维码和条形码"),
    P("base64Image", "developer", "photo.artframe", ["base64Image"], ["text"],
      "Base64 Image", "Base64 图片",
      "Show Base64 or data: image data as an image to copy, save or pin",
      "把 Base64 或 data: 开头的图片数据显示成图片，可以复制、保存、贴到屏幕"),
    P("random", "developer", "dice", ["random"], [],
      "Random", "随机生成",
      "Generate UUIDs, passwords and random numbers to paste into the current field",
      "生成 UUID、密码和随机数字，可以直接粘贴到当前输入框"),
    P("linkInspect", "developer", "link", ["linkInspect"], ["url"],
      "Parse Link", "链接解析",
      "Split a link into scheme, host, path and decoded parameters, and remove tracking parameters such as utm_source",
      "拆开链接的协议、主机、路径和每个参数（解码后），去掉 utm_source 这类跟踪参数"),
    P("jwtDecode", "developer", "key", ["jwtDecode"], ["text"],
      "Decode JWT", "JWT 解码",
      "Decode the selected JWT and list claims such as issuer and expiry (decoding only; the signature isn’t verified)",
      "解码选中的 JWT，列出签发者、过期时间等声明（只解码，不验证签名）"),
    P("regexTest", "developer", "asterisk.circle", ["regexTest"], ["text"],
      "Regex Tester", "正则测试",
      "Try regular expressions on the selected text: live highlighting of matches, groups and replacements",
      "在选中的文字里试正则表达式：实时标出每处匹配、列出分组，也可以试替换"),
    P("cron", "developer", "clock.arrow.circlepath", ["cron"], ["text"],
      "Cron Expression", "Cron 表达式",
      "Explain a cron expression (e.g. */15 9-17 * * 1-5) in words and list the next run times",
      "把 cron 表达式（比如 */15 9-17 * * 1-5）说成中文，列出接下来几次运行的时间"),
    P("codeImage", "developer", "chevron.left.forwardslash.chevron.right", ["codeImage"], ["text"],
      "Code Screenshot", "代码截图",
      "Render the selected code as an image (dark editor, syntax highlighting, gradient background) to copy, save or pin",
      "把选中的代码画成一张图片（深色编辑器、语法着色、渐变背景），可以复制、存储或贴到屏幕上"),
    P("jsonTypes", "developer", "curlybraces.square", ["jsonTypes"], ["json"],
      "JSON to Code", "JSON 转代码",
      "Generate TypeScript, Swift, Go and Kotlin type definitions from the selected JSON",
      "根据选中的 JSON 生成 TypeScript、Swift、Go、Kotlin 的类型定义"),
    P("charInfo", "developer", "character.magnify", ["charInfo"], ["text"],
      "Character Info", "字符信息",
      "See each character’s Unicode code point, name and encoding; find and remove invisible characters such as zero-width spaces",
      "查看每个字符的 Unicode 码点、名称和编码；找出并去掉零宽空格这类看不见的字符"),
    # screen
    P("tableOCR", "screen", "tablecells", ["tableOCR"], [],
      "Recognize Table", "识别表格",
      "Recognize a table in a screenshot or image as a Markdown table, CSV or tab-separated text (macOS 26; earlier versions recognize plain text)",
      "识别截图或图片里的表格，转成 Markdown 表格、CSV 或者制表符分隔（macOS 26；更早的系统按普通文字识别）"),
    P("scanCode", "screen", "qrcode.viewfinder", ["scanCode"], [],
      "Scan Code", "扫码",
      "Select a QR code or barcode on screen to read it; links can be opened and Wi-Fi codes show the password",
      "框选屏幕上的二维码或条形码，识别里面的内容；链接可以直接打开，Wi-Fi 二维码列出密码"),
    P("beautify", "screen", "wand.and.stars", ["beautify"], [],
      "Beautify Screenshot", "截图美化",
      "Put a screenshot on a gradient background with padding, rounded corners and a shadow, optionally filled out to 1:1, 4:3 or 16:9, so it looks good in posts and slides. Uses the selected image, or lets you select an area of the screen first",
      "给截图加上渐变背景、留白、圆角和阴影，可以补成 1:1、4:3、16:9，发文章、做演示更好看；选中图片就用它，没选中就先框选屏幕上的一块"),
    P("removeBackground", "screen", "wand.and.stars", ["removeBackground"], ["image", "imageFile"],
      "Remove Background", "抠图",
      "Remove the background of the selected image, keeping only people, animals or objects (offline)",
      "去掉选中图片的背景，只留下人、动物或物品（离线）"),
    P("imageConvert", "screen", "photo.on.rectangle.angled", ["imageConvert"], ["imageFile"],
      "Convert Images", "图片转换",
      "Convert the selected images to PNG, JPEG or HEIC, halve their size, compress them (or under a given size), rotate, flip, or remove location and capture info; results are saved next to the originals",
      "把选中的图片文件转成 PNG、JPEG、HEIC，缩小一半、压缩体积或者压到指定大小以内，旋转、左右翻转，或者去掉照片里的位置和拍摄信息；结果存在原图旁边"),
    P("stitchImages", "screen", "square.split.1x2", ["stitchImages"], ["imageFile"],
      "Stitch Images", "拼接图片",
      "Stitch the selected images vertically or horizontally in file name order, or make an animated image, saved next to the first one",
      "把选中的几张图片按文件名的顺序竖着或者横着拼成一张，或者合成一张动图，存在第一张旁边"),
    P("splitImage", "screen", "square.grid.3x3", ["splitImage"], ["imageFile"],
      "Split Image", "切分图片",
      "Cut the selected image into a 3 × 3 or 2 × 2 grid (cropped to a square around the subject) or three squares side by side, or cut a long image into pages. The pieces are numbered in posting order and saved in a folder next to the original",
      "把选中的图片切成九宫格、四宫格（对准画面里的主体裁成正方形）或者横着三张，长图切成几页；按发出去的顺序编号，存在原图旁边的文件夹里"),
    P("compareImages", "screen", "square.split.2x1", ["compareImages"], ["files"],
      "Compare Images", "对比图片",
      "Compare two selected images side by side, with a swipe divider or a translucent overlay, or mark the pixels that differ in red and box each area that changed. Handy for before-and-after screenshots and for checking a build against its design",
      "对比选中的两张图片：并排、滑动分界线、半透明叠加，或者把不一样的像素标红、框出几处不同；改版前后的截图、设计稿和实现对照都用得上"),
    P("appIcon", "screen", "app.dashed", ["appIcon"], ["imageFile"],
      "Make App Icon", "生成图标",
      "Make app icons from the selected image: a macOS .icns and an Xcode icon set (a rounded square the size of the system’s app icons), a 1024 iOS icon and a website favicon, saved in a folder next to the image",
      "用选中的图片生成 App 图标：macOS 的 .icns 和 Xcode 用的图标集（圆角方块，和系统 App 的图标一样大）、iOS 的 1024 图标，还有网站的 favicon，存在原图旁边的文件夹里"),
    P("watermark", "screen", "signature", ["watermark"], ["files"],
      "Watermark", "加水印",
      "Tile semi-transparent text diagonally across the selected images or PDFs and save copies next to the originals",
      "给选中的图片或 PDF 斜着铺满一层半透明的文字（比如「仅供办理业务使用」），另存一份放在原文件旁边"),
    P("idPhoto", "screen", "person.crop.rectangle", ["idPhoto"], ["imageFile"],
      "ID Photo", "证件照",
      "Give a portrait a white, blue or red background and crop it around the face to 1-inch or 2-inch ID sizes (300 dpi); processed on this Mac and saved as a copy next to the original",
      "把人像照片换成白底、蓝底或红底，按人脸位置裁成一寸、二寸（300 dpi）；在本机处理，另存一份放在原图旁边"),
    P("cropImage", "screen", "crop", ["cropImage"], ["imageFile"],
      "Crop Image", "裁剪图片",
      "Crop the selected images to 1:1, 4:3, 3:4, 16:9 or 9:16, centered on the subject; a copy is saved next to the original",
      "把选中的图片裁成 1:1、4:3、3:4、16:9、9:16，自动对准画面里的主体；另存一份放在原图旁边"),
    P("redact", "screen", "eye.slash", ["redact"], ["imageFile"],
      "Redact", "隐私打码",
      "Find faces, phone numbers, email addresses, ID and bank card numbers and license plates in the selected images, pixelate them and save a copy; recognized on this Mac, and the copy carries no capture info or location",
      "找出选中图片里的人脸、电话号码、邮箱、身份证号、银行卡号和车牌，打上马赛克另存一份；在本机识别，另存的那份不带拍摄信息和位置"),
    P("palette", "screen", "paintpalette", ["palette"], ["image", "imageFile"],
      "Image Colors", "图片配色",
      "Find the main colors in an image, listed by area; click to copy a value",
      "找出图片里的主要颜色，按面积从大到小列出色值，点一下复制"),
    P("ruler", "screen", "ruler", ["ruler"], [],
      "Screen Ruler", "屏幕标尺",
      "Freeze the screen and measure distances from the pointer to the edges around it; drag to measure an area; click to copy the size",
      "定格屏幕，量出指针处到上下左右边缘的距离，拖动量一块区域的宽高；单击复制尺寸"),
    # recording
    P("screenRecord", "recording", "record.circle", ["screenRecord"], [],
      "Record Screen", "录屏",
      "Drag out an area, click a window or press Return to record the whole screen as MP4; can include the Mac’s sound or the microphone and show clicks and keystrokes, and the recording can then be turned into a GIF. Use it again while recording to stop",
      "拖出一块区域、单击选一个窗口或者按回车录整个屏幕，存成 MP4；可以录上电脑里的声音或者麦克风、显示鼠标点击和按下的键，录好能接着转成 GIF。正在录的时候再用一次就停止"),
    P("voiceRecorder", "recording", "mic", ["voiceRecorder"], [],
      "Voice Recorder", "录音",
      "Record sound from the microphone and save it as an .m4a file in Downloads; while recording, a small bar at the top of the screen shows the time and level and can pause, and you can transcribe the recording afterwards. Use it again while recording to stop",
      "用麦克风录一段声音，存成 .m4a 放进「下载」；录的时候屏幕上方有个小条，看得到时长和音量，可以暂停，录好能接着转成文字。正在录的时候再用一次就停止"),
    P("scrollCapture", "recording", "scroll", ["scrollCapture"], [],
      "Scrolling Screenshot", "滚动截图",
      "Select an area, then scroll down while Pop captures it into one long image: whole web pages, chat histories and long documents, with text recognition afterwards if you like. Use it again while capturing to finish",
      "框选一块区域，一边往下滚动一边截，拼成一张长图；网页、聊天记录、长文档都能截全，还能接着识别文字。正在截的时候再用一次就是完成"),
    P("showKeystrokes", "recording", "command.square", ["showKeystrokes"], [],
      "Show Keystrokes", "显示按键",
      "Show the shortcuts you press (⌘C, ⇧⌘4, arrow keys and so on) at the bottom of the screen for demos and tutorials; ordinary typing isn’t shown. Use it again to turn it off. Screen recordings can include them too",
      "演示、录教程时在屏幕下方显示按下的组合键（⌘C、⇧⌘4、方向键这些），普通打字不显示；再用一次关闭。录屏时也可以勾选一起录进去"),
    P("screenPen", "recording", "scribble.variable", ["screenPen"], [],
      "Draw on Screen", "屏幕画笔",
      "Draw right on the screen for demos and tutorials: pen, highlighter, arrow, rectangle and ellipse. Strokes can fade after a few seconds or stay while you use the windows underneath, and screen recordings include them. Press Esc or use it again to finish",
      "演示、录教程时直接在屏幕上画：画笔、荧光笔、箭头、方框、椭圆，笔迹可以几秒后自动消失，也可以留着去操作下面的窗口，录屏时一起录进去；Esc 或再用一次结束"),
    P("cameraBubble", "recording", "person.crop.circle", ["cameraBubble"], [],
      "Camera Bubble", "摄像头小窗",
      "Show the camera in a small round window in a corner of the screen, so you appear in tutorials and demos. Drag to move it, scroll or double-click to resize, right-click to change the shape or camera. Use it again to close",
      "在屏幕角落用一个圆形小窗显示摄像头画面，录教程、演示时把自己也放进画面；拖动换位置，滚动或双击换大小，右键换形状和摄像头。再用一次关闭"),
    P("pointerHighlight", "recording", "cursorarrow.rays", ["pointerHighlight"], [],
      "Highlight Pointer", "突出显示指针",
      "Put a yellow halo around the pointer that ripples when you click, so people can always find it in demos and tutorials. Use it again to turn it off",
      "演示、录教程时在指针周围加一圈黄色光圈，按下鼠标时泛起波纹，让人一眼看到指针在哪；再用一次关闭"),
    P("spotlight", "recording", "flashlight.on.fill", ["spotlight"], [],
      "Spotlight", "聚光灯",
      "Dim the screen except for a circle around the pointer that follows it, so people look where you point in demos and tutorials. Screen recordings include it; use it again to turn it off",
      "演示、录教程时把屏幕压暗，只亮着指针周围一圈，跟着指针走，让大家看你指的地方；录屏时一起录进去，再用一次关闭"),
    P("zoom", "recording", "plus.magnifyingglass", ["zoom"], [],
      "Screen Zoom", "屏幕放大",
      "Magnify the area around the pointer in demos and tutorials so small text is easy to read. It zooms into a snapshot of the screen: move the pointer to look around, scroll or press ↑↓ to change the magnification, and click or press Esc to go back",
      "演示、录教程时把指针附近放大，看清小字：放大的是那一刻的屏幕画面，挪动指针换地方看，滚轮或 ↑↓ 调倍数，点一下或按 Esc 回去"),
    P("teleprompter", "recording", "text.aligncenter", ["teleprompter"], ["text"],
      "Teleprompter", "提词器",
      "Put the selected script in a teleprompter at the top of the screen that scrolls up at the speed you set, so you can read it to the camera. Space pauses, ↑ and ↓ change the speed, and screen recordings leave it out",
      "把选中的稿子放进屏幕上方的提词器，按设好的速度慢慢往上滚，对着摄像头读；空格暂停，↑↓ 调速度，录屏时不会录进去"),
    # files
    P("folderTree", "files", "list.bullet.indent", ["folderTree"], ["files"],
      "Folder Tree", "目录结构",
      "Write the structure of the selected folder as a tree or Markdown list for docs, READMEs or sharing",
      "把选中文件夹里的目录结构写成树形或者 Markdown 列表，贴进文档、README 或者发给别人"),
    P("codeStats", "files", "chevron.left.forwardslash.chevron.right", ["codeStats"], ["files"],
      "Lines of Code", "代码行数",
      "Count code files and lines per language in the selected folders; copy as a Markdown table",
      "按语言统计选中的文件夹里有多少个代码文件、多少行，可以复制成 Markdown 表格"),
    P("compareFiles", "files", "doc.on.doc", ["compareFiles"], ["files"],
      "Compare Files", "对比文件",
      "Compare the two selected text files (code, Markdown, config, CSV…), marking removed and added lines and the changed words in them; the older file by modification date is the original",
      "对比选中的两个文本文件（代码、Markdown、配置、CSV……），标出删去和新增的行，改动的地方逐词标出；按修改时间，旧的当原文"),
    P("batchRename", "files", "rectangle.and.pencil.and.ellipsis", ["batchRename"], ["files"],
      "Batch Rename", "批量重命名",
      "Rename the selected files together: numbering, find and replace, prefix and suffix, photo capture date, case. Preview first and undo afterwards.",
      "给选中的文件统一改名：编号、替换文字、加前后缀、按照片的拍摄时间、改大小写，先看预览再改，改完可以撤销"),
    P("zip", "files", "doc.zipper", ["zip", "unzip"], ["files"],
      "Zip and Unzip", "压缩和解压",
      "Compress the selected files or folders into a zip in the same folder, or extract the selected zip files into folders next to them",
      "把选中的文件或文件夹压缩成 zip，存在原来的文件夹里；把选中的 zip 解压到旁边的同名文件夹里"),
    P("openInTerminal", "files", "apple.terminal", ["openInTerminal"], ["files"],
      "Open in Terminal", "在终端打开",
      "Open the selected folder in Terminal (for files, the folder they’re in)",
      "在「终端」里打开选中的文件夹（选中文件时打开它所在的文件夹）"),
    P("pdf", "files", "doc.richtext", ["pdf"], ["files"],
      "PDF", "PDF",
      "Combine the selected images and PDFs into one PDF in file name order. With a single PDF, save each page as an image, copy its text, extract or split pages, add page numbers, add or remove a password, or compress it. For a scan, recognize the text and save a copy you can search and copy from",
      "把选中的图片和 PDF 按文件名顺序合成一个 PDF；只选了一个 PDF 时可以把每页存成图片、复制里面的文字、取出其中几页或者拆开、加页码、加密码或者去掉密码，或者压缩；扫描件可以识别文字，另存一份能搜索、复制的 PDF"),
    P("videoConvert", "files", "film", ["videoConvert"], ["files"],
      "Convert Video", "视频转换",
      "Convert the selected videos to GIF or MP4, compress to 720p, extract audio, or make a contact sheet of 16 evenly spaced frames; results are saved next to the originals",
      "把选中的视频转成 GIF、转成 MP4、压缩到 720p、提取音频，或者均匀取 16 帧拼成一张缩略图；结果存在原视频旁边"),
    P("trimMedia", "files", "scissors", ["trimMedia"], ["files"],
      "Trim", "截取片段",
      "Cut a range from the selected audio or video (by start and end time), saved next to the original",
      "截取选中的音频或视频的一段（写上开始和结束的时间），存在原文件旁边"),
    P("transcribe", "files", "captions.bubble", ["transcribe"], ["files"],
      "Transcribe", "语音转文字",
      "Turn speech in recordings and videos into text and SRT subtitles saved next to the original; Mandarin, English, Cantonese and Japanese, recognized on this Mac when it supports it",
      "把录音、视频里说的话转成文字和 SRT 字幕，存在原文件旁边；普通话、英语、粤语、日语，这台 Mac 支持时在本机识别"),
    P("airDrop", "files", "dot.radiowaves.left.and.right", ["airDrop"], ["text", "files", "image"],
      "AirDrop", "隔空投送",
      "Send the selected files, images, links or text to a nearby iPhone, iPad or Mac with AirDrop",
      "用隔空投送把选中的文件、图片、链接或文字发到附近的 iPhone、iPad 或 Mac"),
    P("sendToPhone", "files", "iphone.radiowaves.left.and.right", ["sendToPhone"], [],
      "Send to Phone", "传到手机",
      "Scan a QR code with your phone to download the selected files or images (folders are zipped first) or get the selected text, and upload files from the phone to Downloads. The phone and Mac just need to be on the same Wi-Fi; Android works too.",
      "手机扫码下载选中的文件、图片（文件夹先打包成 zip）或者拿到选中的文字，也能从手机传文件到「下载」文件夹；手机和 Mac 连同一个 Wi-Fi 就行，安卓手机也能用"),
    P("windowLayout", "files", "rectangle.split.2x1", ["windowLayout"], [],
      "Window Layout", "窗口布局",
      "Move the current window to the left or right half, a third, maximize, center it, or move it to another display",
      "把当前窗口放到屏幕的左半边、右半边、三分之一、最大化、居中，或者移到另一个显示器"),
    P("menuShortcuts", "files", "command", ["menuShortcuts"], [],
      "Keyboard Shortcuts", "快捷键一览",
      "List every keyboard shortcut in the current app’s menus; search them and click one to run it",
      "列出当前 App 菜单里的所有快捷键，可以搜索，点一项直接执行"),
    P("keepAwake", "files", "cup.and.saucer", ["keepAwake"], [],
      "Keep Awake", "保持唤醒",
      "Keep the display on and the Mac awake for a while: for reading, presenting or waiting for downloads",
      "一段时间内不让屏幕变暗、电脑睡眠，适合看文档、演示、等下载"),
    P("systemActions", "files", "switch.2", ["systemActions"], [],
      "System Actions", "系统操作",
      "Lock the screen, turn off the display, sleep, start the screen saver, switch between Dark and Light Mode, mute, hide or show desktop icons, show hidden files, or eject all disks",
      "锁屏、熄屏、睡眠、打开屏幕保护程序、切换深色和浅色模式、静音、隐藏或显示桌面图标、显示隐藏文件、推出所有磁盘"),
    P("quitApps", "files", "xmark.app", ["quitApps"], [],
      "Quit Apps", "退出 App",
      "List running apps and how much memory and CPU each one uses. Quit an app with a click, force quit one that doesn’t respond, or quit all the others at once before a meeting or a demo",
      "列出正在运行的 App 和各占多少内存、CPU，一键退出，没有响应的强制退出；也能一下退出其他所有 App，开会、演示前清清场"),
    P("uninstallApp", "files", "trash.square", ["uninstallApp"], ["files"],
      "Uninstall App", "卸载 App",
      "Uninstall the selected app: find the settings, caches and containers it left in your Library, see how much space each takes, and move them to the Trash together. Check only the leftover files to reset the app to a fresh install",
      "卸载选中的 App：连同它在「资源库」里留下的设置、缓存、容器一起找出来，看清各占多大，再一起移到废纸篓；只勾留下的文件，就是把 App 恢复成刚装好的样子"),
    P("appInfo", "files", "info.square", ["appInfo"], ["files"],
      "App Info", "App 信息",
      "See which chips the selected app is built for, who signed it, whether it is notarized and sandboxed, which permissions it may ask for, what it is built with and where it was downloaded from, ready to copy",
      "看选中的 App 是给哪种芯片做的、谁签的名、有没有公证、在不在沙盒里、会要哪些权限、用什么做的、从哪下载的，可以复制下来"),
    P("batteryInfo", "files", "battery.100", ["batteryInfo"], [],
      "Battery Info", "电池信息",
      "See the charge, maximum capacity (health), cycle count, condition and temperature of a MacBook battery, how many watts are going in or out, the charger’s wattage, and how long until it’s full or empty; also lists the battery levels of connected Bluetooth keyboards, mice, trackpads and headphones",
      "看笔记本电池的电量、最大容量（健康度）、循环次数、状况、温度，正在充电或者耗电的功率、充电器多少瓦，还要多久充满或者用完；也列出连着的蓝牙键盘、鼠标、触控板和耳机的电量"),
    P("systemInfo", "files", "info.circle", ["systemInfo"], [],
      "System Info", "系统信息",
      "See this Mac’s model, chip and cores, memory, macOS version, uptime, free space on the startup disk, and each display’s resolution and refresh rate, and copy it all at once for bug reports or when asking for help",
      "看这台 Mac 的型号、芯片和核心数、内存、macOS 版本、开机多久、启动磁盘还剩多少、每台显示器的分辨率和刷新率，可以一键复制，报问题、问人时用"),
    P("soundDevices", "files", "hifispeaker", ["soundDevices"], [],
      "Sound Devices", "声音设备",
      "Switch where sound plays and which microphone is used in one go: speakers, headphones, AirPods, displays or AirPlay, and adjust the volume or mute",
      "一下子换声音从哪出、用哪个麦克风：扬声器、耳机、AirPods、显示器、AirPlay，还能调音量、静音"),
    P("resolution", "files", "display", ["resolution"], [],
      "Resolution", "分辨率",
      "Change each display’s resolution (what it looks like) and refresh rate, or pick the main display; after a change on an external display, click Keep within 15 seconds or it switches back",
      "换显示器的分辨率（看起来像多大）和刷新率，把哪台设成主显示器；外接显示器换了以后 15 秒内不点「保留」就换回原来的"),
    P("diskSpeed", "files", "speedometer", ["diskSpeed"], [],
      "Disk Speed", "磁盘测速",
      "Measure how fast a hard drive, USB stick or portable SSD writes and reads sequentially. Select a file or folder on a disk to test that disk, or nothing to test the startup disk",
      "测硬盘、U 盘、移动固态硬盘连续写入和读取有多快：选中磁盘里的文件或文件夹就测那块盘，什么都不选时测启动磁盘"),
    P("cleanKeyboard", "files", "keyboard", ["cleanKeyboard"], [],
      "Clean Keyboard", "清洁键盘",
      "Lock the keyboard for a minute so you can wipe it without typing anything; brightness and volume keys are blocked too. Click End Cleaning with the mouse to stop any time",
      "锁住键盘一分钟，擦键盘时不会误触；亮度、音量键也不起作用，用鼠标点「结束清洁」随时恢复"),
    P("timer", "files", "timer", ["timer"], [],
      "Timer", "计时器",
      "Countdown: choose a duration, or select text such as “25 min” or “1:30” to start right away. Plays a sound and sends a notification when time’s up. There’s also a Pomodoro timer: 25 minutes of focus, then a 5-minute break, over and over",
      "倒计时：选一个时长，或者选中「25 分钟」「1:30」这样的文字直接开始；到点时响一声、发通知。也有番茄钟：专注 25 分钟、休息 5 分钟，一直循环"),
    P("focusSounds", "files", "headphones", ["focusSounds"], [],
      "White Noise", "白噪音",
      "Play white, pink or brown noise, rain or waves to cover the chatter around you while you focus or nap, with a volume control and a sleep timer. The sound is generated on your Mac and keeps playing after you close the card; pause or stop it from the headphones icon in the menu bar",
      "放白噪音、粉红噪音、棕色噪音、雨声或者海浪，盖住周围的说话声，专心做事、午睡时用；可以调音量、定时停止。声音在本机实时生成，关掉卡片也接着放，菜单栏的耳机图标可以暂停、停止"),
    P("folderTools", "files", "folder.badge.gearshape", ["diskUsage", "findDuplicates", "compareFolders"], ["files"],
      "Folder Tools", "文件夹工具",
      "See what takes up the most space in a folder, find files with identical contents and compare two folders, then move what you don’t need to the Trash",
      "看文件夹里哪些东西最占地方、找出内容一样的重复文件、比较两个文件夹有哪些不同，不要的可以移到废纸篓"),
    P("tidyFolder", "files", "folder.badge.gearshape", ["tidyFolder"], [],
      "Tidy Folder", "整理文件夹",
      "Sort the files at the top of the selected folder (or Downloads if nothing is selected) into subfolders by type or by month, or sort photos and videos by the date they were taken. Preview first and undo afterwards",
      "把选中的文件夹（没选时是「下载」）第一层的文件按类型或者按月份归到子文件夹里，照片和视频也能按拍摄日期归好；先看预览，整理完可以撤销"),
    P("newFile", "files", "doc.badge.plus", ["newFile"], [],
      "New File", "新建文件",
      "Create a text, Markdown, web page or script file in the selected folder (or the folder open in Finder), or save the selected text or the text or image on the clipboard as a file",
      "在选中的文件夹（没选时是访达当前的文件夹）里新建文本、Markdown、网页、脚本这些文件，也可以把选中的文字、剪贴板里的文字和图片直接存成文件"),
    P("fileEncoding", "files", "character.book.closed", ["fileEncoding"], ["files"],
      "File Encoding", "文件编码",
      "See which encoding (UTF-8, GBK, Big5…) and line endings the selected text files use, and convert them to UTF-8 (with a BOM so Excel opens CSV files correctly) or GBK, with LF or CRLF line endings. Undo afterwards",
      "认出选中的文本文件是什么编码（UTF-8、GBK、Big5……）、用的什么换行，一键转成 UTF-8（Excel 打开 CSV 要带 BOM）或者 GBK，换行统一成 LF 或 CRLF；转完可以撤销"),
    P("similarPhotos", "files", "photo.stack", ["similarPhotos"], ["files"],
      "Similar Photos", "相似照片",
      "Find burst shots and photos saved twice or resized in the selected folder (or images), keep the sharpest one of each group and move the rest to the Trash",
      "在选中的文件夹（或者几张图片）里找出连拍、重复存的、改过大小的相似照片，每组留最清楚的一张，其余的移到废纸篓"),
    P("mediaInfo", "files", "film.stack", ["mediaInfo"], ["files"],
      "Media Info", "媒体信息",
      "See the codec, resolution, frame rate and bit rate of the selected video or audio, whether it’s HDR, its audio and subtitle tracks, and which device shot it where; save a copy without the location if it has one",
      "看选中的视频或音频用的什么编码、分辨率、帧率、码率，是不是 HDR，有几条音轨和字幕，用什么设备在哪拍的；带着拍摄地点时可以去掉位置另存一份"),
    P("subtitles", "files", "captions.bubble", ["subtitles"], ["files"],
      "Subtitles", "字幕工具",
      "Shift the selected subtitles (SRT, WebVTT, ASS, LRC) earlier or later, convert between frame rates, remove style tags and hearing-impaired descriptions, and save them as SRT, WebVTT, LRC or plain text; select two to merge them into one bilingual file",
      "选中字幕文件（SRT、WebVTT、ASS、LRC），整体提前或推后、换帧率、去掉样式标签和听障说明，转成 SRT、WebVTT、LRC 或纯文字；选两份字幕可以合成一份双语字幕"),
    P("encryptFiles", "files", "lock.doc", ["encryptFiles"], ["files"],
      "Encrypt Files", "加密打包",
      "Put the selected files and folders into a password-protected (AES-256) disk image that opens on any Mac with a double-click and the password; use it before sending files or saving them to a USB drive or cloud storage",
      "把选中的文件和文件夹放进一个用密码加密（AES-256）的磁盘映像，在任何一台 Mac 上双击、输入密码就能打开；发给别人、存到 U 盘或者网盘前用"),
]


BY_ID = {p.id: p for p in PLUGINS}
assert len(BY_ID) == len(PLUGINS)


def in_cat(key):
    return [p for p in PLUGINS if p.cat == key]


def cat_name(key, lang):
    for k, en, zh, _, _ in CATS:
        if k == key:
            return zh if lang == "zh" else en


def cat_blurb(key, lang):
    for k, _, _, en, zh in CATS:
        if k == key:
            return zh if lang == "zh" else en
